[package]
name = "compression-core"
description = """
Abstractions for compression algorithms.
"""
version = "0.4.27"
authors.workspace = true
license.workspace = true
categories.workspace = true
edition.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
