name: coverage

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/cache-cargo-install-action@v1
      with: { tool: cargo-tarpaulin }
    - run: cargo --locked tarpaulin --all-features -- --skip 'proptest::'
    - uses: codecov/codecov-action@v3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 0 * * 5'
