name: coverage

env:
  RUST_BACKTRACE: 1

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
    - uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
      with: { tool: cargo-tarpaulin }
    - run: cargo --locked tarpaulin --all-features -- --skip 'proptest::'
    - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
  - cron: '0 0 * * 5'
