name: deny

env:
  RUST_BACKTRACE: 1

jobs:
  cargo-deny-advisories:
    name: cargo deny advisories
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
      with:
        command: check advisories

  cargo-deny-licenses:
    name: cargo deny bans licenses sources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
      with:
        command: check bans licenses sources

on:
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
