name: docs

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  docsrs:
    name: cargo doc --cfg docsrs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '--cfg=docsrs -Dwarnings'
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-index-

    - run: cargo doc --all-features --no-deps

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]
