name: docs

env:
  RUST_BACKTRACE: 1

jobs:
  docsrs:
    name: cargo doc --cfg docsrs
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: '--cfg=docsrs -Dwarnings'
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        toolchain: nightly
    - run: cargo doc --all-features --no-deps

on:
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
